server:
  port: 8002
eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8001/eureka
spring:
  rabbitmq:
    addresses: localhost:5672
    host: localhost
    port: 5672
    usename: guest
    password: guest
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: ping
        uri: lb://ping
        predicates:
        - Path=/v1/ping/**
        filters:
        - RewritePath=/v1/ping/(?<path>.*), /$\{path}
  zipkin:
    sender:
      type: rabbit
  sleuth:
    sampler:
      percentage: 1.0
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: "*"
---

spring:
  profiles: docker
