version: "3"

services:
  mysql:
    image: mysql:5.7
    expose:
    - '3306'
    ports:
    - '3306:3306'
    environment:
    - MYSQL_ROOT_PASSWORD=123456
    - MYSQL_USER=cms
    - MYSQL_PASSWORD=123456
    - MYSQL_DATABASE=charmmy
  redis:
    image: bitnami/redis:latest
    expose:
    - '6379'
    ports:
    - '6379:6379'
    environment:
    - REDIS_PASSWORD=123456
  kafka:
    image: thaitv/docker-kafka:1.0.0
    container_name: kafka
    expose:
    - '9092'
    ports:
    - "9092:9092"
    environment:
    - KAFKA_ADVERTISED_HOST_NAME=localhost
    - KAFKA_ADVERTISED_PORT=9092
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
    - zookeeper
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
    - "2181:2181"
    environment:
    - KAFKA_ADVERTISED_HOST_NAME=zookeeper
  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    restart: always
    environment:
    - RABBIT_ADDRESSES=rabbitmq:5672
    ports:
    # Port used for the Zipkin UI and HTTP Api
    - "8008:9411"
    depends_on:
    - rabbitmq
  rabbitmq:
    image: rabbitmq:management
    expose:
      - '5672'
      - '15672'
    ports:
    - 5672:5672
    - 15672:15672
#  elasticsearch:
#    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.0
#    container_name: elasticsearch
#    expose:
#      - '9200'
#      - '9300'
#    ports:
#      - "9200:9200"
#      - "9300:9300"
#  kibana:
#    image: docker.elastic.co/kibana/kibana:6.4.0
#    container_name: kibana
#    expose:
#      - "5601"
#    ports:
#      - "5601:5601"
##    links:
##      - elasticsearch:es
#    depends_on:
#      - elasticsearch
#  logstash:
#    image: docker.elastic.co/logstash/logstash:6.4.0
#    container_name: logstash
#    expose:
#      - "5044"
#    ports:
#      - "5044:5044"