version: "3"

services:
  mysql:
    image: mysql:5.7
    expose:
    - '3306'
    ports:
    - '3306:3306'
    environment:
    - MYSQL_ROOT_PASSWORD=123456
    - MYSQL_USER=cms
    - MYSQL_PASSWORD=123456
    - MYSQL_DATABASE=charmmy
  redis:
    image: bitnami/redis:latest
    expose:
    - '6379'
    ports:
    - '6379:6379'
    environment:
    - REDIS_PASSWORD=123456
  kafka:
    image: thaitv/docker-kafka:1.0.0
    container_name: kafka
    expose:
    - '9092'
    ports:
    - "9092:9092"
    environment:
    - KAFKA_ADVERTISED_HOST_NAME=localhost
    - KAFKA_ADVERTISED_PORT=9092
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
    - zookeeper
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
    - "2181:2181"
    environment:
    - KAFKA_ADVERTISED_HOST_NAME=zookeeper
  rabbitmq:
    image: rabbitmq:management
    ports:
    - 5672:5672
    - 15672:15672